### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by jeffg-dev**

### CODE REVIEW

**Comment by ellieayla** [comment]
@jeffgreenca This file is the result of a build process, so we should really fix the source instead. I'm having trouble reading the diff -- what is the typo?

**Comment by jeffg-dev** [comment]
Hard to read this diff? You don't say! :p

> The Ingetsion API is part of the Query API

**Comment by ellieayla** [comment]
Thanks; I've got this in an internal bug 1990716 for @mavagyan

**Comment by jeffg-dev** [comment]
Closing so this can be fixed in upstream.  Thanks.

**Pull request closed without merging**
